export const raceOptions = [
  { value: "Dragonborn", label: "Dragonborn" },
  { value: "Dwarf", label: "Dwarf" },
  { value: "Elf", label: "Elf" },
  { value: "Gnome", label: "Gnome" },
  { value: "Half-Elf", label: "Half-Elf" },
  { value: "Half-Orc", label: "Half-Orc" },
  { value: "Halfling", label: "Halfling" },
  { value: "Human", label: "Human" },
  { value: "Tiefling", label: "Tiefling" },
];

export const classTypeOptions = [
  { value: "Cleric", label: "Cleric" },
  { value: "Fighter", label: "Fighter" },
  { value: "Rogue", label: "Rogue" },
  { value: "Wizard", label: "Wizard" },
];

export const levelOptions = [
  { value: 1, label: 1 },
  { value: 2, label: 2 },
  { value: 3, label: 3 },
  // Add more levels as required
];

export const numbersArray = Array.from({ length: 24 }, (_, index) => index + 1);

export const locations = [
  "abandoned buildings",
  "alien dimension",
  "ambush sites",
  "battlegrounds",
  "caves",
  "caverns",
  "coastal caves",
  "coastal cliffs",
  "cold caves",
  "deep caves",
  "desert sandy caverns",
  "drow cities",
  "duergar fortresses",
  "dungeons",
  "dungeons sewers",
  "dwarven halls",
  "elven cities",
  "forests",
  "fortresses",
  "glades",
  "graveyards",
  "haunted places",
  "icy mountains",
  "jungles",
  "lair",
  "magma caverns",
  "marshes",
  "mountain caverns",
  "mountain fortresses",
  "mountains",
  "oceans",
  "patrol routes",
  "plains",
  "ritual sites",
  "rocky terrains",
  "ruins",
  "strongholds",
  "swamps",
  "temples",
  "tombs",
  "tundras",
  "underground",
  "underground cities",
  "underdark",
  "volcanoes",
  "wastelands",
  "war camps",
  "warm caves",
];
